name: BDD Tests

on:
  workflow_dispatch:  # This enables manual trigger of the workflow

jobs:
  run-bdd-tests:
    runs-on: ubuntu-latest  # You can choose any available runner

    steps:
      - name: Set up Node.js (LTS Version)
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # This uses the latest LTS version of Node.js

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Start Test Application
        run: npm run start:test-app &
        env:
          NODE_ENV: test

      - name: Run BDD Tests
        run: npm run test:bdd

      - name: Kill Application
        if: always()  # This ensures the step runs regardless of the outcome of the previous steps
        run: kill $(lsof -t -i:3000 -sTCP:LISTEN) || echo "Failed to kill process. Might have already stopped."
